apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: url-shortner-ingress
  namespace: url-shortner
spec:
  ingressClassName: nginx
  rules:
    - host: url-shortner.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: url-shortner-service
                port:
                  number: 80
