apiVersion: v1
kind: Service
metadata:
  name: url-shortner-service
spec:
  type: NodePort
  selector:
    app: url-shortner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
